solEs4.x: solEs4.o ../Librerie/libACaso.o ../Librerie/puntoR2.o
	g++ solEs4.o ../Librerie/libACaso.o ../Librerie/puntoR2.o -o solEs4.x

libACaso.o: ../Librerie/libACaso.C ../Librerie/libACaso.h
	g++ -c ../Librerie/libACaso.C

puntoR2.o: ../Librerie/puntoR2.C ../Librerie/puntoR2.h
	g++ -c ../Librerie/puntoR2.C



solEs4.o: solEs4.C
	g++ -c solEs4.C





